namespace CoreWindowsWrapper.Api.Ole
{
    public enum tagDESCKIND
    {
        /// DESCKIND_NONE -> 0
        DESCKIND_NONE = 0,

        /// DESCKIND_FUNCDESC -> DESCKIND_NONE+1
        DESCKIND_FUNCDESC = (DESCKIND_NONE + 1),

        /// DESCKIND_VARDESC -> DESCKIND_FUNCDESC+1
        DESCKIND_VARDESC = (DESCKIND_FUNCDESC + 1),

        /// DESCKIND_TYPECOMP -> DESCKIND_VARDESC+1
        DESCKIND_TYPECOMP = (DESCKIND_VARDESC + 1),

        /// DESCKIND_IMPLICITAPPOBJ -> DESCKIND_TYPECOMP+1
        DESCKIND_IMPLICITAPPOBJ = (DESCKIND_TYPECOMP + 1),

        /// DESCKIND_MAX -> DESCKIND_IMPLICITAPPOBJ+1
        DESCKIND_MAX = (DESCKIND_IMPLICITAPPOBJ + 1),
    }
}