namespace CoreWindowsWrapper.Api.Ole
{
    public enum tagOLEMISC
    {
        /// OLEMISC_RECOMPOSEONRESIZE -> 0x1
        OLEMISC_RECOMPOSEONRESIZE = 1,

        /// OLEMISC_ONLYICONIC -> 0x2
        OLEMISC_ONLYICONIC = 2,

        /// OLEMISC_INSERTNOTREPLACE -> 0x4
        OLEMISC_INSERTNOTREPLACE = 4,

        /// OLEMISC_STATIC -> 0x8
        OLEMISC_STATIC = 8,

        /// OLEMISC_CANTLINKINSIDE -> 0x10
        OLEMISC_CANTLINKINSIDE = 16,

        /// OLEMISC_CANLINKBYOLE1 -> 0x20
        OLEMISC_CANLINKBYOLE1 = 32,

        /// OLEMISC_ISLINKOBJECT -> 0x40
        OLEMISC_ISLINKOBJECT = 64,

        /// OLEMISC_INSIDEOUT -> 0x80
        OLEMISC_INSIDEOUT = 128,

        /// OLEMISC_ACTIVATEWHENVISIBLE -> 0x100
        OLEMISC_ACTIVATEWHENVISIBLE = 256,

        /// OLEMISC_RENDERINGISDEVICEINDEPENDENT -> 0x200
        OLEMISC_RENDERINGISDEVICEINDEPENDENT = 512,

        /// OLEMISC_INVISIBLEATRUNTIME -> 0x400
        OLEMISC_INVISIBLEATRUNTIME = 1024,

        /// OLEMISC_ALWAYSRUN -> 0x800
        OLEMISC_ALWAYSRUN = 2048,

        /// OLEMISC_ACTSLIKEBUTTON -> 0x1000
        OLEMISC_ACTSLIKEBUTTON = 4096,

        /// OLEMISC_ACTSLIKELABEL -> 0x2000
        OLEMISC_ACTSLIKELABEL = 8192,

        /// OLEMISC_NOUIACTIVATE -> 0x4000
        OLEMISC_NOUIACTIVATE = 16384,

        /// OLEMISC_ALIGNABLE -> 0x8000
        OLEMISC_ALIGNABLE = 32768,

        /// OLEMISC_SIMPLEFRAME -> 0x10000
        OLEMISC_SIMPLEFRAME = 65536,

        /// OLEMISC_SETCLIENTSITEFIRST -> 0x20000
        OLEMISC_SETCLIENTSITEFIRST = 131072,

        /// OLEMISC_IMEMODE -> 0x40000
        OLEMISC_IMEMODE = 262144,

        /// OLEMISC_IGNOREACTIVATEWHENVISIBLE -> 0x80000
        OLEMISC_IGNOREACTIVATEWHENVISIBLE = 524288,

        /// OLEMISC_WANTSTOMENUMERGE -> 0x100000
        OLEMISC_WANTSTOMENUMERGE = 1048576,

        /// OLEMISC_SUPPORTSMULTILEVELUNDO -> 0x200000
        OLEMISC_SUPPORTSMULTILEVELUNDO = 2097152,
    }
}