namespace CoreWindowsWrapper.Api.Ole
{
    public enum tagOLEGETMONIKER
    {
        /// OLEGETMONIKER_ONLYIFTHERE -> 1
        OLEGETMONIKER_ONLYIFTHERE = 1,

        /// OLEGETMONIKER_FORCEASSIGN -> 2
        OLEGETMONIKER_FORCEASSIGN = 2,

        /// OLEGETMONIKER_UNASSIGN -> 3
        OLEGETMONIKER_UNASSIGN = 3,

        /// OLEGETMONIKER_TEMPFORUSER -> 4
        OLEGETMONIKER_TEMPFORUSER = 4,
    }
}